# Generated by Django 2.1.3 on 2018-11-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('longitude', models.CharField(max_length=15)),
                ('latitude', models.CharField(max_length=15)),
                ('all_distances_calculated', models.BooleanField(default=False)),
                ('adjacent_nodes', models.ManyToManyField(related_name='_node_adjacent_nodes_+', to='router.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='distance',
            name='node_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_start_distances', to='router.Node'),
        ),
        migrations.AddField(
            model_name='distance',
            name='node_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_end_distances', to='router.Node'),
        ),
    ]
