# Generated by Django 2.1.3 on 2018-11-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='adjacent_nodes',
            field=models.ManyToManyField(blank=True, related_name='_node_adjacent_nodes_+', to='router.Node'),
        ),
    ]
