# Generated by Django 2.1.3 on 2018-11-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_auto_20181124_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance', models.IntegerField()),
                ('time', models.IntegerField()),
                ('node_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_start_edges', to='router.Node')),
                ('node_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_end_edges', to='router.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='distance',
            name='node_1',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='node_2',
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
