# Generated by Django 2.1.3 on 2018-11-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0004_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='latitude',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='node',
            name='longitude',
            field=models.CharField(max_length=30),
        ),
    ]
