# Generated by Django 2.1.3 on 2018-11-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0006_auto_20181125_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='has_bus_stop',
            field=models.BooleanField(default=False),
        ),
    ]
