# Generated by Django 2.1.3 on 2018-11-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0007_edge_has_bus_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_gate',
            field=models.BooleanField(default=False),
        ),
    ]
