# Generated by Django 2.1.3 on 2018-11-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0010_auto_20181125_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('height', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('turn_radius', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
