# Generated by Django 2.1.3 on 2018-11-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0011_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='end_edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks_ending', to='router.Edge'),
        ),
        migrations.AddField(
            model_name='truck',
            name='end_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks_ending', to='router.Node'),
        ),
        migrations.AddField(
            model_name='truck',
            name='start_edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks_starting', to='router.Edge'),
        ),
        migrations.AddField(
            model_name='truck',
            name='start_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks_starting', to='router.Node'),
        ),
    ]
