# Generated by Django 2.1.3 on 2018-11-25 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0012_auto_20181125_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='router.Route'),
        ),
    ]
