# Generated by Django 2.1.3 on 2018-11-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0015_auto_20181125_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='max_height',
            field=models.FloatField(default=15),
        ),
        migrations.AlterField(
            model_name='edge',
            name='max_weight',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='edge',
            name='max_width',
            field=models.FloatField(default=15),
        ),
    ]
